# Generated by Django 5.1.7 on 2025-04-02 13:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('street', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('landmark', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('city', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('state', models.CharField(choices=[('ap', 'Andhra Pradesh'), ('ar', 'Arunachal Pradesh'), ('as', 'Assam'), ('br', 'Bihar'), ('cg', 'Chhattisgarh'), ('ga', 'Goa'), ('gj', 'Gujarat'), ('hr', 'Haryana'), ('hp', 'Himachal Pradesh'), ('jk', 'Jammu & Kashmir'), ('jh', 'Jharkhand'), ('ka', 'Karnataka'), ('kl', 'Kerala'), ('mp', 'Madhya Pradesh'), ('mh', 'Maharashtra'), ('mn', 'Manipur'), ('ml', 'Meghalaya'), ('mz', 'Mizoram'), ('nl', 'Nagaland'), ('od', 'Odisha'), ('pb', 'Punjab'), ('rj', 'Rajasthan'), ('sk', 'Sikkim'), ('tn', 'Tamil Nadu'), ('tg', 'Telangana'), ('up', 'Uttar Pradesh'), ('ut', 'Uttarakhand'), ('wb', 'West Bengal'), ('an', 'Andaman and Nicobar Islands'), ('ch', 'Chandigarh'), ('dn', 'Dadra and Nagar Haveli and Daman and Diu'), ('dl', 'Delhi'), ('ld', 'Lakshadweep'), ('py', 'Puducherry')], max_length=255)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(regex='^\\d{6}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('duration', models.CharField(help_text='input value in month', max_length=255)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_email', models.EmailField(max_length=255, unique=True)),
                ('employee_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Enter a valid 10-digit number', regex='^\\d{10}$')])),
                ('dob', models.DateField()),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10)),
                ('role', models.CharField(choices=[('trainer', 'Trainer'), ('coordinator', 'Coordinator'), ('other', 'Other')], max_length=255)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.address')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('batch_start_date', models.DateField()),
                ('batch_end_date', models.DateField()),
                ('batch_start_time', models.TimeField()),
                ('batch_end_time', models.TimeField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.course')),
                ('coordinator', models.ForeignKey(limit_choices_to={'role': 'coordinator'}, on_delete=django.db.models.deletion.RESTRICT, related_name='coordinator', to='app1.employee')),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 'trainer'}, on_delete=django.db.models.deletion.RESTRICT, to='app1.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Learners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('qualification', models.CharField(choices=[('ssc', 'SSC'), ('hsc', 'HSC'), ('diploma', 'Diploma'), ('graduate', 'Graduate'), ('post_graduate', 'PG')], max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10)),
                ('enrollement_date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.address')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_enrolled_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='active', max_length=100)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.batch')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.learners')),
            ],
            options={
                'unique_together': {('batch', 'learner')},
            },
        ),
    ]
